# See https://deno.land/manual/advanced/continuous_integration

on: [push,pull_request]

# Set DENO_DIR to an absolute or relative path on the runner.
env:
  DENO_AUTH_TOKENS: ${{ secrets.DENO_AUTH_TOKENS }}
  DENO_DIR: cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the code and steup deno with latest stable version
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1

      # Run all test files in the repository and collect code coverage
      - run: deno test --allow-all --coverage=cov/
      - run: deno coverage --lcov cov/ > cov.lcov

      # Upload to Codecov (see https://github.com/marketplace/actions/codecov)
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: cov.lcov

      # Check that code is correctly formatted
      # TODO: Format code and commit back (see https://mskelton.medium.com/ed458f58b7df)
      - run: deno fmt --check
